version: '3.8'
services: 
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped
    networks:
      - mongodb-network

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    container_name: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
    depends_on:
      - mongodb
    ports:
      - 37017:8081
    restart: unless-stopped
    networks:
      - mongodb-network

networks:
  mongodb-network:
    name: mongodb-network