version: '3.8'
services: 
  mongodb:
    image: mongo:5.0.2
    container_name: mongodb
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=root
    #   - MONGO_INITDB_ROOT_PASSWORD=pass123
    ports: 
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    restart: unless-stopped
    networks:
      - mongodb-network

  # mongo-express:
  #   image: mongo-express:1.0.0-alpha.4
  #   container_name: mongo-express
  #   environment:
  #     - ME_CONFIG_MONGODB_SERVER=mongodb
  #     - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
  #     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
  #     - ME_CONFIG_MONGODB_ADMINPASSWORD=pass123
  #     - ME_CONFIG_BASICAUTH_USERNAME=admin
  #     - ME_CONFIG_BASICAUTH_PASSWORD=admin123
  #   depends_on:
  #     - mongodb
  #   ports:
  #     - 37017:8081
  #   restart: unless-stopped
  #   networks:
  #     - mongodb-network

networks:
  mongodb-network:
    name: mongodb-network